#!/usr/bin/env python
import os
from os.path import abspath, dirname, join
top_level = dirname(dirname(abspath(__file__)))
os.chdir(top_level)
ini = join(top_level, 'development.ini') 
os.system('paster serve --reload %s' % ini)
