#!/usr/bin/env python
"""Run the `paster serve` command.

The first arg to this script is the ini file to use. All following args are
passed to paster as --options. If no args are given to this script,
development.ini is used with the --reload option.

"""
import sys
import os
from os.path import abspath, dirname, join

# Change this if the Python you're using to run the Pylons app wasn't
# installed in $HOME
prefix = os.environ['HOME']

args = sys.argv

# Goto the top level of the project
top_level = dirname(dirname(abspath(__file__)))
os.chdir(top_level)

# ini file name to pass to `paster serve`
try:
    ini = args[1]
except IndexError:
    ini = 'development'

if not ini.endswith('.ini'):
    ini = ini + '.ini'
ini = join(top_level, ini)

# Args to pass to `paster serve`
try:
    args[2]
except IndexError:
    args = ['reload']
    print 'Using default args: %s' % args
else:
    args = args[2:]    

    
# Run `paster serve` with args and ini file
args = ' --'.join([''] + args)
ini = os.path.split(ini)[-1]
cmd = '%s/bin/paster serve %s %s' % (prefix, args, ini)
                                     
print cmd
os.system(cmd)
