# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "days", :force => true do |t|
    t.column "name", :string
  end

  create_table "events", :force => true do |t|
    t.column "name",        :string
    t.column "location_id", :integer
    t.column "day_id",      :integer
    t.column "start_time",  :time
  end

  create_table "locations", :force => true do |t|
    t.column "name",        :string
    t.column "description", :text
    t.column "latitude",    :float
    t.column "longitude",   :float
    t.column "address",     :string
    t.column "city",        :string
    t.column "state",       :string,  :limit => 2
    t.column "zip",         :integer
  end

# Could not dump table "zt01_d00" because of following StandardError
#   Unknown type 'polygon' for column 'the_geom'

end
