# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "days", :force => true do |t|
    t.column "name", :string
  end

  create_table "events", :force => true do |t|
    t.column "name", :string
    t.column "location_id", :integer
    t.column "day_id", :integer
    t.column "start_time", :time
  end

  create_table "locations", :force => true do |t|
    t.column "name", :string
    t.column "description", :text
    t.column "latitude", :float
    t.column "longitude", :float
    t.column "address", :string
    t.column "city", :string
    t.column "state", :string, :limit => 2
    t.column "zip", :integer
  end

  create_table "zt01_d00", :options=>'ENGINE=MyISAM', :force => true do |t|
    t.column "AREA", :float
    t.column "PERIMETER", :float
    t.column "ZT01_D00_", :integer
    t.column "ZT01_D00_I", :integer
    t.column "ZCTA", :string
    t.column "NAME", :string
    t.column "LSAD", :string
    t.column "LSAD_TRANS", :string
    t.column "the_geom", :polygon, :null => false
  end

  add_index "zt01_d00", ["the_geom"], :name => "zt01_d00_the_geom_spatial_index", :spatial=> true 

end
